config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "books#home"
  get "/select_search", to: "books#select_search",
    as: "select_search"
  get "/search_book", to: "books#search_book",
    as: "search_book"
  get "/admin_search", to: "books#admin_search",
    as: "admin_search"

  resources :books
  resources :authors
  resources :categories
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category

  validates :name, presence: true,
    length: {maximum: Settings.book.max_name}
  validates :price, presence: true
  validates :public_date, presence: true
  validates :category_id, presence: true
  mount_uploader :image, PictureUploader
  validate :image_size
  BOOK_PARAMS = %w(name category_id description
    image author_id price public_date).freeze
  BOOK_ATTR = %w(id name description price public_date
    image category_id _destroy).freeze
  PRICE_MIN = 1
  PRICE_MEDIUM = 2
  DATE_BEFORE = 1
  DATE_MIDDLE = 2
  MUSTY_THREE = 3
  MUSTY_SEVEN = 7
  MUSTY_TEN = 10

  scope :find_category, ->(id){where(category_id: id)}
  scope :find_author, ->(id){where(author_id: id)}
  scope :price_min, lambda{
    where("price >= #{MUSTY_THREE}
      and price <= #{MUSTY_SEVEN}")
  }
  scope :price_medium, lambda{
    where("price > #{MUSTY_SEVEN}
      and price < #{MUSTY_TEN}")
  }
  scope :price_max, ->{where("price >= 10")}
  scope :before_musty, ->{where("public_date < '#{Date.new(2012, 1, 1)}'")}
  scope :middle_musty, lambda{
    where("public_date >= '#{Date.new(2012, 1, 1)}'
      and public_date < '#{Date.new(2015, 1, 1)}'")
  }
  scope :after_musty, ->{where("public_date >= '#{Date.new(2015, 1, 1)}'")}
  scope :find_name, ->(name){where("name LIKE ?", "%#{name}%")}
  scope :search_books, lambda{|content|
    joins(:author, :category)
      .where("books.name LIKE ? or books.description LIKE ? or price LIKE ?
        or authors.name LIKE ? or categories.name LIKE ?", "%#{content}%",
        "%#{content}%", "%#{content}%", "%#{content}%", "%#{content}%")
  }

  class << self
    def search params
      books = Book.all

      category_id = params[:category_id].to_i
      author_id = params[:author_id].to_i
      price = params[:price].to_i
      public_date = params[:public_date].to_i

      unless params[:category_id].blank?
        books = books.find_category(category_id)
      end
      books = books.find_author(author_id) unless params[:author_id].blank?
      unless params[:price].blank?
        books = if price == PRICE_MIN
                  books.price_min
                elsif price == PRICE_MEDIUM
                  books.price_medium
                else
                  books.price_max
                end
      end
      unless params[:public_date].blank?
        books = if public_date == DATE_BEFORE
                  books.before_musty
                elsif public_date == DATE_MIDDLE
                  books.middle_musty
                else
                  books.after_musty
                end
      end
      books
    end
  end

  private
  def image_size
    return unless image.size > Settings.image.capacity.megabytes
    errors.add :image, "should be less than 5MB"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: %i(show edit update destroy)
  before_action :authenticate_user!, except: %i(home select_search search_book)
  
  def home
    @books = Book.all
  end

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = "Successfully created..."
      redirect_to books_path
    else
      flash[:danger] = "Fail created..."
      render :new
    end
  end

  def destroy
    @book.destroy
  end

  def edit; end

  def update
    if @book.update_attributes book_params
      flash[:success] = "Update successfull!"
      redirect_to books_path
    else
      flash[:danger] = "Fail"
      render :edit
    end
  end

  def select_search
    @books = Book.search params
  end

  def search_book
    @name = params[:name_search]
    return @books = Book.find_name(@name) unless @name.empty?
    @books = Book.all
  end

  def admin_params
    @search = params[:search]
    @table = params[:table]
    @search_cate = params[:search_cate]
  end

  def table_category search
    return @records = Category.search_categories(search) unless
      search.blank?
    @records = Category.all
  end

  def table_author search
    return @records = Author.search_author(search) unless search.blank?
    @records = Author.all
  end

  def table_book search
    @records = Book.all
    @records = Book.find_category(params[:category]) unless
      params[:category].blank?
    @records = Book.find_category(params[:search_cate]) unless
      params[:search_cate].blank?
    @records = @records.search_books(search) unless search.blank?
  end

  def admin_search
    admin_params
    if @table == "author"
      table_author @search
    elsif @table == "category"
      table_category @search
    elsif @table == "book"
      table_book @search
    end
  end

  private
  def book_params
    params.require(:book).permit Book::BOOK_PARAMS
  end

  def find_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = "Do not find category..."
    redirect_to books_path
  end
end

app/views/books/_book.html.erb
<div class="col-md-12">
  <%= form_for @book do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.label :category_id %>
    <br>
    <%= f.select(:category_id,
      [[ "Choose Category", 0]] + Category.all.map{ |c| [c.name, c.id] }) %>
    <br><br>
    <br>
    <%= f.select(:author_id,
      [[ "Choose Author", 0]] + Author.all.map{ |c| [c.name, c.id] }) %>
    <br><br>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name",
        class: "form-control", placeholder: "Enter Name Category" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_area :description, class: "form-control", rows: 5 %>
    </div>
    <div class="form-group">
      <%= f.label :price %><br />
      <%= f.number_field :price, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :image %>
      <div class="img-medium">
      <%= image_tag @book.image.url if @book.image? %>
      </div>
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png",
        class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :public_date %><br />
      <%= f.date_field :public_date, as: :date,
        value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
    </div>
    <%= f.submit "Submit form", class: "btn btn-default sign-up" %>
  <% end %>
</div>

app/views/books/_detail_book.html.erb
<% if @books.present? %>
  <%= render "list_books" %>
<% else %>
  <h1>Nothing</h1>
<% end %>

app/views/books/_detail_search_admin.html.erb
<% if @records.count > 0 %>
  <% @records.each do |record| %>
    <% if @table == "category" %>
      <tr id="categories_<%= record.id %>">
        <td>
          <%= link_to admin_search_path(category: record.id, table: "book") do %>
            <%= record.name %>
          <% end %>
        </td>
        <td><%= record.description %></td>
        <td>
          <%= link_to edit_category_path(record.id) do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        </td>
        <td>
          <%= hidden_field_tag :category_id, record.id, class: "category_id" %>
          <i class="glyphicon glyphicon-remove-circle rmv_category"></i>
        </td>
      </tr>
    <% elsif @table == "book" %>
      <tr id="books_<%= record.id %>">
        <td><%= record.name %></td>
        <td>
          <%= link_to edit_category_path(record.category.id) do %>
            <%= record.category.name %>
          <% end %>
        </td>
        <td><%= record.author.name %></td>
        <td><%= record.description %></td>
        <td><%= number_to_currency record.price %></td>
        <td><%= record.public_date %></td>
        <td>
          <% if record.image? %>
            <%= image_tag record.image.url, class: "show_img" %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_book_path(record.id) do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        </td>
        <td>
          <%= hidden_field_tag :book_id, record.id, class: "book_id" %>
          <i class="glyphicon glyphicon-remove-circle rmv_book"></i>
        </td>
      </tr>
    <% elsif @table == "author" %>
      <tr id="authors_<%= record.id %>">
        <td><%= record.name %></td>
        <td>
          <%= link_to edit_author_path(record.id) do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        </td>
        <td>
          <%= hidden_field_tag :author_id, record.id, class: "author_id" %>
          <i class="glyphicon glyphicon-remove-circle rmv_author"></i>
        </td>
      </tr>
    <% else %>
    <% end %>
  <% end %>
<% else %>
  <tr>
    <td style="color:red">
      Not found record
    </td>
  </tr>
<% end %>

app/views/books/_list_book.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Author</th>
      <th>Description</th>
      <th>Price</th>
      <th>Public date</th>
      <th>Image</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody class="result_search">
    <% @books.each do |book| %>
      <tr id="books_<%= book.id %>">
        <td><%= book.name %></td>
        <td>
          <%= link_to edit_category_path(book.category.id) do %>
            <%= book.category.name %>
          <% end %>
        </td>
        <td><%= book.author.name %></td>
        <td><%= book.description %></td>
        <td><%= number_to_currency book.price %></td>
        <td><%= book.public_date %></td>
        <td>
          <% if book.image? %>
            <%= image_tag book.image.url, class: "show_img" %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_book_path(book.id) do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        </td>
        <td>
          <%= hidden_field_tag :book_id, book.id, class: "book_id" %>
          <i class="glyphicon glyphicon-remove-circle rmv_book"></i>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_list_books.html.erb
<% i = 0 %>
<% @books.each do |book| %>
  <% i += 1 %>
  <div class="col-sm-4">
    <div class="single-item">
      <div class="single-item-header">
        <%= link_to "#" do %>
          <%= image_tag book.image.url, class: "size_book" if book.image? %>
        <% end %>
      </div>
      <h3 class="single-item-title" style="margin-bottom:15px">
        <%= book.name %>
      </h3>
      <div class="item_book">
        <%= link_to "#", class: "detals_book" do %>
          Xem chi tiết 
          <i class="glyphicon glyphicon-menu-right"></i>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
  <% if i%3 == 0 %>
    <div class="col-md-12" id="space_row"></div>
  <% end %>
<% end %>

app/views/books/admin_search.html.erb
<div class="col-md-12">
  <%= render "layouts/sidebar" %>
  <div class="col-md-10">
    <h2 style="text-align:center">
      Books
    </h2>
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>Search:</th>
            <th rowspan="2">Category</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= hidden_field_tag :article_id, "book", class: "table_book" %>
              <%= text_field_tag :search, params[:search],
                class: "admin_search form-control", id: "book_search" %>
            </td>
            <td rowspan="2">
              <%= select_tag "admin_category",options_for_select(
                [[ "Choose Category", ""]] + @categories.map{ |c| [c.name, c.id] },
                selected: params[:category]),
                class: "slect_admin_category form-control" %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Author</th>
            <th>Description</th>
            <th>Price</th>
            <th>Public date</th>
            <th>Image</th>
            <th>Edit</th>
            <th>Remove</th>
          </tr>
        </thead>
        <tbody class="result_search">
          <%= render "detail_search_admin" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
  

app/views/books/edit.html.erb
<div class="col-md-12">
  <%= render "layouts/sidebar" %>
  <div class="col-md-10">
    <h2 style="text-align:center">
      Update book
    </h2>
    <%= render "books/book" %>
  </div>
</div>
  

app/views/books/home.html.erb
<%= render "layouts/slide" %>
<div class="col-md-12 result_book">
  <h1 class="name_web all_book">All books</h1>
  <%= render "list_books" %>
</div>

app/views/books/index.html.erb
<div class="col-md-12">
  <%= render "layouts/sidebar" %>
  <div class="col-md-10">
    <h2 style="text-align:center">
      All books
    </h2>
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>Search:</th>
            <th rowspan="2">Category</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= hidden_field_tag :article_id, "book", class: "table_book" %>
              <%= text_field_tag :search, params[:search],
                class: "admin_search form-control", id: "book_search" %>
            </td>
            <td rowspan="2">
              <%= select_tag "admin_category",options_for_select(
                [[ "Choose Category", ""]] + @categories.map{ |c| [c.name, c.id] },
                selected: params[:category]),
                class: "slect_admin_category form-control" %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= render "list_book" %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="col-md-12">
  <%= render "layouts/sidebar" %>
  <div class="col-md-10">
    <h2 style="text-align:center">
        Create new book
    </h2>
    <%= render "books/book" %>
  </div>
</div>