config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "books#home"
  get "/select_search", to: "books#select_search",
    as: "select_search"
  get "/search_book", to: "books#search_book",
    as: "search_book"
  get "/admin_search", to: "books#admin_search",
    as: "admin_search"

  resources :books
  resources :authors
  resources :categories
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Books Store", root_path,
        class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active">    
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span> Home
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to categories_path do %>
            <i class="fa fa-database"> Manage</i>
          <% end %>
        </li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <% if current_user.image? %>
              <%= image_tag current_user.image.url,
                class: "img-circle image_user" %>
            <% end %>
            <%= current_user.name %> 
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Logout", destroy_user_session_path,
                method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span> Sign Up
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span> Login
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-md-2 sidle_bar">
  <li>    
    <a href="#">
      <span class="fa fa-database"></span> Manage
    </a>
  </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <span class="glyphicon glyphicon-leaf"></span> Categories 
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to categories_path do %>
          <i class="fa fa-film"> List categories</i>
        <% end %>
      </li>
      <li>
        <%= link_to new_category_path do %>
          <i class="fa fa-plus-square"> New category</i>
        <% end %>
      </li>
    </ul>
  </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <span class="fa fa-book"></span> Books 
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to books_path do %>
          <i class="fa fa-book"> List books</i>
        <% end %>
      </li>
      <li>
        <%= link_to new_book_path do %>
          <i class="fa fa-plus-square"> New book</i>
        <% end %>
      </li>
    </ul>
  </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <span class="fa fa-user"></span> Authors 
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to authors_path do %>
          <i class="fa fa-book"> List authors</i>
        <% end %>
      </li>
      <li>
        <%= link_to new_author_path do %>
          <i class="fa fa-user-plus"> New author</i>
        <% end %>
      </li>
    </ul>
  </li>
</div>

app/views/layouts/_slide.html.erb
<div class="col-md-12 search_book">
  <div class="col-md-3">
    <label for="cate" class="label_select">Category</label><br>
    <%= select_tag "category",options_for_select(
      [[ "Choose Category", ""]] + @categories.map{ |c| [c.name, c.id] }),
      class: "slect_form_category slect_form" %>
  </div>
  <div class="col-md-2">
    <label for="au" class="label_select">Author</label><br>
    <%= select_tag "author",options_for_select(
      [[ "Choose Author", ""]] + @authors.map{ |c| [c.name, c.id] }),
      class: "slect_form_author slect_form" %>
  </div>
  <div class="col-md-2">
    <label for="pri" class="label_select">Price</label><br>
    <%= select_tag "price", options_for_select(
      [["Choose Price", ""], ["3$ - 7$", 1], ["7$ - 10$", 2], ["> 10$", 3]]),
      class: "slect_form_price slect_form" %>
  </div>
  <div class="col-md-3">
    <label for="date" class="label_select">Public date</label><br>
    <%= select_tag "public_date", options_for_select(
      [["Choose Public Date", ""], ["Before 2012", 1],
        ["2012 - 2015", 2], ["After 2012", 3]]),
      class: "slect_form_date slect_form" %>
  </div>
  <div class="col-md-2">
    <label for="sel1" class="label_select">Search book</label><br>
    <%= text_field_tag :search_book, params[:name],
      class: 'form-control slect_form', id: "search_book" %>
  </div>
</div>
<div class="col-md-12 slide_ruby">
  <div id="carousel-example-generic" class="carousel slide" 
    data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag "img1.jpg", class: "img-responsive slide-image" %>
        <%= image_tag "img2.jpg", class: "slide-image" %>
        <%= image_tag "img3.jpg", class: "slide-image" %>
        <%= image_tag "img4.jpg", class: "slide-image" %>
        <%= image_tag "img5.jpg", class: "slide-image" %>
        <%= image_tag "img6.jpg", class: "slide-image" %>
      </div>
      <div class="item">
        <%= image_tag "img7.jpg", class: "slide-image" %>
        <%= image_tag "img8.jpg", class: "slide-image" %>
      </div>
    </div>
    <%= link_to "#carousel-example-generic",
      class: "left carousel-control", data: {slide: "prev"} do %>
      <span class="glyphicon glyphicon-chevron-left"></span>
    <% end %>
    <%= link_to "#carousel-example-generic",
      class: "right carousel-control", data: {slide: "next"} do %>
      <span class="glyphicon glyphicon-chevron-right"></span>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div id="flash">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>
          </div>
        <% end %>
      </div>
      <div class="content">
        <%= yield %>
      </div> 
    </div>
  </body>
</html>